name: Build and Push Splunk Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    # Step 8: Build Docker image
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/splunk-custom:latest .

      # Step 9: Push Docker image to GHCR
    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/splunk-custom:latest

    - name: Run main branch tasks
      run: echo "Running workflow for main branch."

   
