name: Build and Push Splunk Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t splunk-custom:latest .
        
    - name: Push Docker image
      run: |
        docker tag splunk-custom:latest yourdockerhubusername/splunk-custom:latest
        docker push yourdockerhubusername/splunk-custom:latest
